### ISSUE TITLE
[Change Log] Issue

### ISSUE THREAD

**Issue by CatsArmy** [mattymatty97/LTC_TooManyItems#1]
The change log is just the same as the Lobby Control change log it seems to be that it has not been adjusted accordingly to the new mods id honestly not even update the mod for this id wait for a code change ngl

**Comment by mattymatty97** [comment]
😂 you are right, i forgot to clear the Changelog file

**Comment by mattymatty97** [comment]
but i doubt there will ever be a new update so i might better update the changelog now
